name: highlight_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  ffmpeg_kit_flutter_video: ^6.0.3
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
